# Generated by Django 4.1.5 on 2023-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=500)),
                ("phone", models.CharField(max_length=500)),
            ],
        ),
    ]
