# Generated by Django 4.1.5 on 2023-01-26 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namel', models.CharField(max_length=500)),
                ('userl', models.CharField(max_length=100)),
                ('datecl', models.DateField(default=datetime.datetime(2023, 1, 26, 4, 13, 35, 64022, tzinfo=datetime.timezone.utc))),
                ('dateml', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='contacto',
        ),
    ]
